-- Add token tracking columns to audit_logs table
ALTER TABLE arao.text_to_sql.audit_logs
ADD COLUMNS (
  prompt_tokens BIGINT COMMENT 'Number of input tokens sent to LLM',
  completion_tokens BIGINT COMMENT 'Number of output tokens generated by LLM',
  total_tokens BIGINT COMMENT 'Total tokens used (prompt + completion)',
  estimated_cost_usd DOUBLE COMMENT 'Estimated cost in USD based on model pricing',
  business_logic_length INT COMMENT 'Length of business logic text',
  generated_sql_length INT COMMENT 'Length of generated SQL text'
);
