command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

# Allow anonymous access to the app
default_source_ip_permissions:
  - action: ALLOW
    ip_addresses: ["0.0.0.0/0"]

env:
  - name: ENV
    value: "production"
  - name: PORT
    value: "8000"
  - name: DEBUG
    value: "False"
  - name: DATABRICKS_HOST
    value: "https://fe-vm-leaps-fe.cloud.databricks.com"
  - name: DATABRICKS_TOKEN
    valueFrom: queryforge/databricks-token
  - name: DATABRICKS_CATALOG
    value: "arao"
  - name: DATABRICKS_SCHEMA
    value: "text_to_sql"
  - name: DATABRICKS_HTTP_PATH
    value: "/sql/1.0/warehouses/2dc6b7aacc451bcd"
