-- Create schema if it doesn't exist
CREATE SCHEMA IF NOT EXISTS arao.text_to_sql;

-- Create audit_logs table for tracking all activities
CREATE TABLE IF NOT EXISTS arao.text_to_sql.audit_logs (
  log_id STRING,  -- UUID generated by application
  timestamp TIMESTAMP,
  event_type STRING,  -- 'sql_generation', 'business_logic_suggestion', 'sql_execution'
  user_id STRING,
  catalog STRING,
  schema_name STRING,
  table_name STRING,
  columns ARRAY<STRING>,
  business_logic STRING,
  generated_sql STRING,
  model_id STRING,
  execution_time_ms BIGINT,  -- Time taken for the operation in milliseconds
  row_count BIGINT,  -- Number of rows returned (for sql_execution)
  status STRING,  -- 'success', 'error'
  error_message STRING,
  metadata MAP<STRING, STRING>  -- Additional metadata as needed
)
USING DELTA;
